source 'http://rubygems.org'

gem 'gosu'
gem 'hash-to-ostruct'

group :test do
  gem 'guard'
  gem 'guard-rspec'
  gem 'debugger'
  gem 'rspec'
  gem 'rcov'
  gem 'rake'
  gem 'roodi'
  gem 'flog'
  gem 'flay'
end
